<?php
/**
 * mystatus.tpl.php
 * Copyright 2012 The Honors Program at RIT
 *
 * ===================
 * Available Variables
 * ===================
 * ALWAYS DEFINED
 * $username
 * $status - Continuation Status (as an integer)
 * $status_string - Continuation Status (plain text)
 * $points_total - integer total honors points
 * $complearning_status - integer status
 * $complearning_status_string - plaintext status
 *
 * SOMETIMES NULL
 * $college - college e.g. KGCOE
 * $department - e.g. Electrical Engineering
 * $program - e.g. 'BS', 'BS/MS'
 * $name - full name
 * $gpa - plain text representation of gpa
 * $year - user's year level
 * $courses - array of courses taken
 *    - each element is an array with keys 'num','name','term','grade','points','instructor'
 * $points username, explanation,
 *  	pointID as type,
 * 		submitted as submitted_time,
		submittedBy as submitted_by,
		approved as status,
		approvedBy as reviewer,
		approvedTime as reviewed_time,
		declinedReason as reason,
		numPoints as credits
 * 
 * TODO
 * -figure out how "other points" will work
 * -figure out how complearning submissions will work
 */
 

if($displaynone):
?>
<h2>You are not in the Honors Database</h2>
<?php else: ?>

<div style="float:right;">
<img src="<?php print base_path()."facebook/portraits/$username.jpg";?>" width=150 height=200 alt="<?php print $username; ?>" />
</div>

<h2>Continuation Status </h2>

 <p>Your continuation status is 
<?php
//provide a background color for select statuses
switch($status){
    case 0: $color = '#A2EB81';break;//green
    case 1: $color = '#D0EB81';break;//green-yellow
    case 2: $color = '#E7EB81';break;//yellow
    case 3: $color = '#EB8181';break;//red
}
//print opening tag  
if(isset($color)){
    print "<span style=\"background-color:$color\" >";
}
?>

<strong><?php print $status_string; ?></strong>

<?php if(isset($color)){ print '</span>'; }/*print closing tag.*/ ?>
</p>

<section>

<h2><?php t('Honor Status for @user',array('@user'=>$username)); ?></h2>

<div id="student-information" style="display:inline-block;width:575px;">
<h2>Student Information</h2>
<div class="paragraph" style="border-left: 2px solid #a4883b; padding-left: 10px">
<table>
    <thead>
        <tr><td>Full Name</td>
        <td>College</td>
        <td>Department</td>
        <td></td>
        <td>GPA</td></tr>
    </thead>
    <tbody>
        <tr><td><?php print $name;?></td>
        <td><?php print $college;?></td>
        <td><?php print $department;?></td>
        <td><?php print $program;?></td>
        <td><?php print substr(strval($gpa),0,1) .'.'.substr(strval($gpa),1);?></td></tr>
    </tbody>
</table>
</div>

<h2> Honors Points</h2>
<div class="paragraph" style="border-left: 2px solid #a4883b; padding-left: 10px">
<strong>Total Points: <?php print (int)$points_total; ?></strong>
<h3> Honors Courses</h3>
<?php print theme('hstatus_courses_table',$courses); ?>

<h3>Other Activities</h3>
<?php echo theme('hstatus_points_table',$points); ?>

<h3><?php echo l("Points Submission Form", "hpoints/form"); ?></h3>

</div>
<h2>Comp Learning Submissions</h2>
<div class="paragraph" style="border-left: 2px solid #a4883b; padding-left: 10px">
<p>Your complearning has been <strong><?php print $complearning_status_string; ?></strong></p>
<p>For requirements, please see the <?php echo l("comp learning page", "service-requirements"); ?> </p>
<h4>Submissions</h4>
<?php echo theme('hstatus_complearn_table',$submissions['complearn']); ?>

</div>
</div> <!-- End #student-information -->
</section> <!-- End Main Section -->
<h2>Questions?</h2>

<h3>Continuation Review</h3>
<p>Email any questions to <a href="mailto:honors@rit.edu">
honors@rit.edu</a></p>

<h3>Comp Learning</h3>
<p><?php echo l( "info about comp learning requirements","service-requirements");?></p>
<p>Email any questions to <a href="mailto:CompLearning@mail.honors.rit.edu">CompLearning@mail.honors.rit.edu</a></p>

<h3>General Requirements</h3>
<p><?php echo l("info about honors requirements", "academic-requirements");?></p>
<p>Email any questions to <a href="mailto:Council@mail.honors.rit.edu">Council@mail.honors.rit.edu</a></p>

<h3>Honors Courses</h3>
<p><?php echo l("A Listing of the currently offered honors courses", "courseslist")?></p>
<p><?php echo l("Academic Requirements", "academic-requirements")?></p>
<p>Email any questions to <a href="mailto:Council@mail.honors.rit.edu">Council@mail.honors.rit.edu</a></p>

<pre>
<?php print_r($huser); /*DEBUG*/ ?>
</pre>
<aside><p>Generated by the hStatus module</p></aside>

<?php endif; ?>

