<?php
/**
 * mystatus.tpl.php
 * Copyright 2012 The Honors Program at RIT
 *
 * ===================
 * Available Variables
 * ===================
 * ALWAYS DEFINED
 * $username
 * $status - Continuation Status (as an integer)
 * $status_string - Continuation Status (plain text)
 * $points_total - integer total honors points
 * $complearning_status - integer status
 * $complearning_status_string - plaintext status
 *
 * SOMETIMES NULL
 * $college - college e.g. KGCOE
 * $department - e.g. Electrical Engineering
 * $program - e.g. 'BS', 'BS/MS'
 * $name - full name
 * $gpa - plain text representation of gpa
 * $year - user's year level
 * $courses - array of courses taken
 *    - each element is an array with keys 'num','name','term','grade','points','instructor'
 * 
 * TODO
 * -figure out how "other points" will work
 * -figure out how complearning submissions will work
 */
 
if($displaynone):
?>
<h2>You are not in the Honors Database</h2>
<?php else: ?>

<h2><?php t('Honor Status for @user',array('@user'=>$username)); ?></h2>
<table>
    <thead>
        <tr><td>Fullname</td>
        <td>College</td>
        <td>Department</td>
        <td></td>
        <td>GPA</td></tr>
    </thead>
    <tbody>
        <tr><td><?php print $name;?></td>
        <td><?php print $college;?></td>
        <td><?php print $department;?></td>
        <td><?php print $program;?></td>
        <td><?php print $gpa;?></td></tr>
    </tbody>
</table>

<p>Your complearning has been <strong><?php print $complearning_status_string; ?></strong></p>

<p>Your continuation status is 
<?php
//provide a background color for select statuses
switch($status){
    case 0: $color = '#A2EB81';break;//green
    case 1: $color = '#D0EB81';break;//green-yellow
    case 2: $color = '#E7EB81';break;//yellow
    case 3: $color = '#EB8181';break;//red
}
//print opening tag  
if(isset($color)){
    print "<span style=\"background-color:$color\" >";
}
?>

<strong><?php print $status_string; ?></strong>

<?php if(isset($color)){ print '</span>'; }/*print closing tag.*/ ?>
</p>
<pre>
<?php print_r($huser); /*DEBUG*/ ?>
</pre>
<aside><p>Generated by the hStatus module</p></aside>

<?php endif; ?>

