<?php

/* hnews.install
 * 
 * Doesn't do much, but it is still necessary
 */

function hnews_install(){
    $oldengine = variable_get('mimemail_engine', 'mimemail');
    variable_set('mimemail_engine', 'hnews');
    variable_set('hnews_old_mailengine', $oldengine);
}

function hnews_uninstall(){
    $oldengine = variable_get('hnews_old_mailengine', 'mimemail');
    variable_set('mimemail_engine', $oldengine);
    variable_del('hnews_old_mailengine');
}
