<?php
/*
 * Will need to declare plenty of permissions.
 */
function hstudent_perm() {
	return array(
		'Administer hstudent module',
		'Search students',
		'Search faculty'
	);
}

/*
 * Need to register a path for the search page (and possibly a results page).
 * Only register this page if the user has the appropriate permissions.
 */
function hstudent_menu() {
	items['search_users'] = array(
		'title' => "Search Users",
		'page_callback' => '_hstudent_search_page',
		'access_callback' => '_hstudent_search_access'
	);
	// items['search_results'] = array(
		// 'title' => "Search Results",
		// 'page_callback' => '_hstudent_results_page',
		// 'access_callback' => '_hstudents_results_access',
		// 'type' => MENU_CALLBACK
	// );
}

/*
 * Page callback for .../search_users/
 * Generates search page
 */
function _hstudent_search_page($arg) {
}

/*
 *Generates search form, and results if a search has been initiated
 */
function hstudent_search_form($form_state) {
	$form['search_field'] = array(
		'#type' => 'textfield',
		'#title' => t('Name(s) or RIT DCE:')
	);
	$form['submit_button'] = array(
		'#type' => 'submit',
		'#value' => t('Search')
	);
	if($form_state['search_field']) {
		//Generate search results
	}
	return $form;
}

/*
 * Access callback for URL .../search_users/
 * Specifies access permissions for the search page
 */
function _hstudent_search_access($arg) {

}

/*
 * Page callback for URL .../search_results/
 * Generates results page
 */
function _hstudent_results_page($arg) {

}

/*
 * Access callback for URL .../search_results/
 * Specifies access permissions for results page
 */
function _hstudent_results_access($arg) {

}