<?php
/*
 * Will need to declare plenty of permissions.
 */
function hstudent_perm() {
	return array(
		'Administer hstudent module',
		'Search students',
		'Search faculty'
	);
}

/*
 * Need to register a path for the search page (and possibly a results page).
 * Only register this page if the user has the appropriate permissions.
 */
function hstudent_menu() {
	items['search_users'] = array(
		'title' => "Search Users",
		'page_callback' => '_hstudent_search_page',
		'access_callback' => '_hstudent_search_access'
	);
	items['search_results'] = array(
		'title' => "Search Results",
		'page_callback' => '_hstudent_results_page',
		'access_callback' => '_hstudents_results_access',
		'type' => MENU_CALLBACK
	);
}

/*
 * Searches for the user with the given name or RIT DCE
 */
function hstudent_search($name) {
	$tokens = explode(' ',$name);
	
	$DCEs = array();
	$names = array();
	foreach($tokens as $s) {
		if(preg_match('/[a-zA-Z]{3}[0-9]{4}/')) {
			//definitely a student DCE
			$DCEs[] = $s;
		} else {
			//not a DCE
			$names[] = $s;
		}
	}
	
	/*Prioritize search results:
	 * 1. DCE match - top priority
	 * 2. First and last name match
	 * 3. One name match
	 */
	$search_results[];
	foreach($DCEs as $s) {
		$query = "SELECT student.firstname firstname,
		                 student.lastname lastname,
						 student.uid uid
				  FROM {h_student} student
				  WHERE student.name = '%s'";
		$result = db_query($query, %s);
		while($arry = db_fetch_array($result)) {
			//Create link string: 'FirstName LastName (DCE)'
			$arry['precedence'] = 0;
			$search_results[] = $arry;
		}
	}
	if(count($names) == 2) {
		$query = "SELECT student.name username,
		                 student.firstname firstname,
						 student.lastname lastname,
						 student.uid uid
				  FROM {h_student} student
				  WHERE (firstname = '%s' AND lastname = '%s') OR
				        (firstname = '%s' AND lastname = '%s')";
		$result = db_query($query, $names[0], $names[1], $names[1], $names[0]);
		while($arry = db_fetch_array($result)) {
			$arry['precedence'] = 1;
			$search_results[] = $arry;
		}
	}
	foreach($names as $s) {
		$query = "SELECT student.name username,
		                 student.firstname firstname,
						 student.lastname lastname,
						 student.uid uid
		          FROM {h_student} student
				  WHERE firstname = '%s' OR lastname = '%s'";
		$result = db_query($query, $s, $s);
		while($arry = db_fetch_array($result)) {
			$arry['precedence'] = 2;
			$search_results[] = $arry;
		}
	}
	//TODO: link to status page with text being the first and last names
}

/*
 * Page callback for .../search_users/
 * Generates search page
 */
function _hstudent_search_page($arg) {

}

/*
 * Access callback for URL .../search_users/
 * Specifies access permissions for the search page
 */
function _hstudent_search_access($arg) {

}

/*
 * Page callback for URL .../search_results/
 * Generates results page
 */
function _hstudent_results_page($arg) {

}

/*
 * Access callback for URL .../search_results/
 * Specifies access permissions for results page
 */
function _hstudent_results_access($arg) {

}