<?php

/**
 * @file hvite.module
 * 
 * This file must be located in the hvite folder and is loaded on every
 * page.
 */

function hvite_menu()
{
	/* Event creation page */
	$items['hvite/createevent'] = array(
		'type' => MENU_NORMAL_ITEM,
		'title' => 'hVite Event Creation Test Form',
		'page arguments' => array(1),
		'page callback' => 'stuff',
		'access arguments' => array(1),
		'access callback' => 'hvite_access_use',
	);
	
	/* Event list page */
	$items['hvite/eventlist'] = array(
		'type' => MENU_NORMAL_ITEM,
		'title' => 'hVite Event List Test Form',
		'page arguments' => array(1),
		'page callback' => 'stuff',
		'access arguments' => array(1),
		'access callback' => 'hvite_access_use',
	);
	
	return $items;
}

/*
 * Form for creating an event
 */
function hvite_createevent_form(&$form_state)
{
	/* Event details */
	$form['details'] = array(
		'#type' => 'fieldset',
		'#title' => t('Event details'),
		'#tree' => TRUE,
	);
	
	/* Title */
	$form['details']['title'] = array(
		'#type' => 'textfield',
		'#title' => t('Event title'),
		'#cols' => 60,
		'#rows' => 5,
		'#description' => t('Max: 100 characters'),
	);
	
	/* Location */
	$form['details']['location'] = array(
		'#type' => 'textfield',
		'#title' => t('Event location'),
		'#cols' => 60,
		'#rows' => 5,
		'#description' => t('Max: 100 characters'),
	);
	
	/* Description */
	$form['details']['description'] = array(
		'#type' => 'textarea',
		'#title' => t('Event description'),
		'#cols' => 60,
		'#rows' => 5,
		//'#description' => t('Event description.'),
	);
	
	/* Start date and time */
	$form['details']['startdate'] = array(
		'#type' => 'date_popup', // types 'date_text' and 'date_timezone' are also supported. See .inc file.
		'#title' => t('Start date and time'),
		'#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
		'#date_year_range' => '-3:+3', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
	);
	
	/* End date and time */
	$form['details']['enddate'] = array(
		'#type' => 'date_popup', // types 'date_text' and 'date_timezone' are also supported. See .inc file.
		'#title' => t('End date and time'),
		'#date_label_position' => 'within', // See other available attributes and what they do in date_api_elements.inc
		'#date_year_range' => '-3:+3', // Optional, used to set the year range (back 3 years and forward 3 years is the default).
	);
	
	/* Submit button */
	$form['submit'] = array('#type' => 'submit', '#value' => t('Create event'));

	return $form;
}

function hvite_createevent_form_validate($form, &$form_state)
{
	if ($form_state['values']['details']['title'] == '')
	{
		form_set_error('title', t('You must enter a title.'));
	}
	if ($form_state['values']['details']['location']  == '')
	{
		form_set_error('location', t('You must enter a location.'));
	}
	if ($form_state['values']['details']['description'] == '')
	{
		form_set_error('description', t('You must enter a description.'));
	}
	if (!isset($form_state['values']['details']['startdate']))
	{
		form_set_error('startdate', t('You must enter a start date.'));
	}
	if (!isset($form_state['values']['details']['enddate']))
	{
		form_set_error('enddate', t('You must select an end date.'));
	}
}

function hvite_createevent_form_submit($form, &$form_state)
{
	$str = "Title: '" . $form_state['values']['details']['title'] . "'<br />";
	$str .= "Location: '" . $form_state['values']['details']['location'] . "'<br />";
	$str .= "Description: '" . $form_state['values']['details']['description'] . "'<br />";
	$str .= "Start date: '" . $form_state['values']['details']['startdate'] . "' (" . strtotime($form_state['values']['details']['startdate']) . ")<br />";
	$str .= "End date: '" . $form_state['values']['details']['enddate'] . "' (" . strtotime($form_state['values']['details']['enddate']) . ")<br />";
	drupal_set_message(t('Event created.'));
	drupal_set_message(t($str));
}

/**
 * Generates the page
 */
function stuff()
{
	return drupal_get_form('hvite_createevent_form');
}

/**
 * Implements hook_perm
 * 
 * Just returns an array of strings to be used on the permissions page
 */
function hvite_perm(){
    return array('make hVite events', 'RSVP to hVite events');
}

/*----------------Access Callbacks------------------*/
function hvite_access_use($account)
{
    if (user_access('make hVite events'))
	{
        return TRUE;
    }
	
	return FALSE;
}
