<?php

function hformtools_elements(){
    // The following definitions were adapted from system_elements in system.module (line 164)
    $type['hformtools_users'] = array(
        '#input' => TRUE,
        '#cols' => 60,
        '#rows' => 5,
        '#resizable' => TRUE,
        '#process' => array('form_expand_ahah'),
    );
    $type['hformtools_html5_number'] = array(
        '#input' => TRUE,
        '#size' => 60,
        '#maxlength' => 128,
        '#autocomplete_path' => FALSE,
        '#process' => array('form_expand_ahah'),
    );
    $type['hformtools_html5_email'] = array(
        '#input' => TRUE,
        '#size' => 60,
        '#maxlength' => 128,
        '#autocomplete_path' => FALSE,
        '#process' => array('form_expand_ahah'),
    );
    return $type;
}

function hformtools_theme($existing, $type, $theme, $path){
    $hooks['hformtools_users'] = array(
        'template' => 'users/form-element',
        'file' => 'users/hformtools_users.inc',
        'arguments' => array('element' => null),
    );
    $hooks['hformtools_html5_number'] = array(
        'arguments' => array('element' => null),
    );
    $hooks['hformtools_html5_email'] = array(
        'arguments' => array('element' => null),
    );
    return $hooks;
}

function theme_hformtools_html5_number($element) { return ""; }
function theme_hformtools_html5_email($element) { return ""; }

function hformtools_menu(){
    $menu['hformtools/ajax/users/group/%'] = array(
        'title' => 'hFormTools AJAX Callback - Group',
        'type' => MENU_CALLBACK,
        'page callback' => 'hformtools_users_ajax_groups',
        'page arguments' => array(4),
        'access callback' => true,
        'file' => 'users/hformtools_users.inc',
    );
    $menu['hformtools/test'] = array(
        'title' => 'Test hFormTools',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('hformtools_testform'),
        'access callback' => true,
    );
    return $menu;
}

function hformtools_testform(&$form_state){
    if(is_array($form_state['storage']['lastsubmission'])){
        $form['lastsub'] = array(
            '#prefix' => '<pre>',
            '#suffix' => '</pre>',
            '#value' => print_r($form_state['storage']['lastsubmission']),
            '#default_value' => 'dtsgla',
        );
    }
    /*$form['html5_number'] = array(
        '#type' => 'hformtools_html5_number',
        '#title' => 'HTML5 Number',
    );
    $form['html5_email'] = array(
        '#type' => 'hformtools_html5_email',
        '#title' => 'HTML5 Email',
    );*/
    $form['users'] = array(
        '#type' => 'hformtools_users',
        '#title' => 'AJAX Users',
    );
    return $form;
}
    
function hformtools_testform_submit($form, &$form_state){
    $form_state['storage']['lastsubmission'] = $form_state['values'];
}
