<?php
/**
 * mystatus.tpl.php
 * Copyright 2012 The Honors Program at RIT
 *
 * ===================
 * Available Variables
 * ===================
 * ALWAYS DEFINED
 * $username
 * $status - Continuation Status (as an integer)
 * $status_string - Continuation Status (plain text)
 * $points_total - integer total honors points
 * $complearning_status - integer status
 * $complearning_status_string - plaintext status
 *
 * SOMETIMES NULL
 * $name - full name
 * $gpa - plain text representation of gpa
 * $year - user's year level
 * $courses - array of courses taken
 *    - each element is an array with keys 'num','name','term','grade','points','instructor'
 * 
 * TODO
 * -figure out how "other points" will work
 * -figure out how complearning submissions will work
 */
?>

<h2>Honors Status for <?php print $username; ?></h2>
<p>Generated by the hStatus module</p>
<p>Your continuation status is <strong><?php print $status_string; ?></strong></p>

