<?php

/**
 * @file hpoints.module
 *
 * This file must be located in the hpoints folder and is loaded on every
 * page.
 */



/*--------------Defaults-------------*/
define('HPOINTS_SUBMIT_MSG','Please describe the activity that you believe should earn you points.');
define('HPOINTS_SUBMIT_WARN','Submissions will be reviewed and you will recieve an email when a decision is made.');

/**
 * Implements hook_menu
 *
 * hook_menu is called by drupal whenever a module is enabled or disabled
 * to update the internal page registry.
 *
 * Note that every page has a built-in permissions callback ("access callback")
 * that determines if (1) it should be shown in menus and (2) if a user
 * can visit it (throws a 403 on false)
 */
//DONE:
function hpoints_menu(){
    //AJAX callback
    //see docs for hpoints_cl_submission
    $items['hpoints/submission/%'] = array(
        'title' => 'Points Submission',
        'page callback' => 'hpoints_submission',
        'page arguments' => array(2),
        'type' => MENU_CALLBACK,
        //access callback defaults to user access
        'access arguments' => array('review points submissions', 'administer points submissions'),
    );

    //complearning form
    //note that even though no % is in the path, anything following 'submitcl' gets passed as an argument.
    //(This is true of all menu entries with blank type)
    $items['hpoints/form'] = array(
        'title' => 'Honors Points Submission Form',
        'page callback' => 'hpoints_build_clform',
        'file' => 'hpoints.form.inc',
        'access arguments' => array('submit points', 'bulk submit points'),
    );
    
    //Settings Page
    //TODO: needs two pages (as tabs) one for types
    $items['admin/settings/hpoints'] = array(
        'title' => 'hPoints Settings',
        'description' => 'Adjust the points form settings.',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('hpoints_admin_settings'),
        'file' => 'hpoints.admin.inc',
        'access arguments' => array('administer points submissions'),
    );
    
    return $items;
}

/**
 * hpoints_cl_submission is an AJAX callback function to generate
 * HTML from complearning submission data.
 *
 * The design intent of this function was that it would be used to
 * return HTML to an AJAX lightbox embedded in a general complearning
 * reviewing page.  As such, it does not display general information
 * such as username, total hours, or time submitted.  It merely gets the
 * submission data and themes it with the theme hook "hpoints_cl_activity"
 */
//DONE:
function hpoints_submission($sid){
    //TODO: write this function
    $points = hdata_points_load($sid);
    $data = $points['data'];
    if($data){
        $output = theme('hpoints_display',$data);
    }else{
        $output = '<h1>Not Found</h1>';
    }

    //AJAX functions should echo the output and return null to prevent
    //the theme system from kicking in.
    echo $output;
    return null;
}

/**
 * Implements hook_perm
 *
 * Just returns an array of strings to be used on the permissions page
 */
//DONE:
function hpoints_perm(){
    return array('submit points', 'bulk submit points',
        'administer points submissions', 'review points submissions');
}

/**
 * Implements hook_theme
 *
 * hook_theme defines "theme hooks" which are just functions or files that
 * generate HTML.  The benefit of doing this is that it makes it easy for
 * other modules or themes to override your display.
 */
//DONE:
function hpoints_theme($existing, $type, $theme, $path){
    return array(
        'hpoints_display' => array(
            'arguments' => array('submission' => NULL),
            'template' => 'pointsubmission',
        ),
    );
}

/**
 * Implements hook_action_info
 */
function hpoints_action_info(){
    return array(
        'hpoints_approve_cl_action' => array(
            'description' => t('Approve Comp Learning Submission'),
            'type' => 'complearning',
            'configurable' => FALSE,
        ),
        'hpoints_reject_cl_action' => array(
            'description' => t('Reject Comp Learning Submission'),
            'type' => 'complearning',
            'configurable' => FALSE,
        ),
    /* Example action -- taken from Drupal
      'user_block_ip_action' => array(
      'description' => t('Ban IP address of current user'),
      'type' => 'user',
      'configurable' => FALSE,
      'hooks' => array(
        'nodeapi' => array('presave', 'delete', 'insert', 'update', 'view'),
        'comment' => array('view', 'insert', 'update', 'delete'),
        'user' => array('logout'),
      )
    ),*/
  );
}

/**
 * Performs a database update to approve a Complearning submission,
 * provided that the user has the appropriate permissions.
 */
function hpoints_approve_cl_action($submission){
    if(user_access('review complementary learning')){
        $id = $submission['id'];
        db_query('UPDATE {h_cl} SET status=1 WHERE id=%d',$id);
    }else{
        drupal_set_message(t('You do not have sufficient priviledges to perform this action.'),'warning');
    }
}
/**
 * Performs a database update to reject a Complearning submission,
 * provided that the user has the appropriate permissions.
 */
function hpoints_reject_cl_action($submission){
    if(user_access('review complementary learning')){
        $id = $submission['id'];
        db_query('UPDATE {h_cl} SET status=2 WHERE id=%d',$id);
    }else{
        drupal_set_message(t('You do not have sufficient priviledges to perform this action.'),'warning');
    }
}

/**
 * Helper function to get type options
 * 
 * //VERDICT: keep this function,but read from h_points_menu
 *      (and let's add some columns to h_points_menu, shall we?
 */
function hpoints_get_type_options(){
    $options_setting = variable_get('hpoints_form_type_options',_hpoints_default_type_options());
    //use CR+LF line ending b/c that how textarea text is formatted.
    $lines = explode("\r\n",$options_setting);
    $options = array();
    foreach($lines as $line){
        $line = trim($line);
        $tokens = explode('|',$line);
        if(count($tokens) == 2){
            $options[$tokens[0]] = $tokens[1];
        }else{
            watchdog('hcomplearn','Malformed type options '.$line,null,WATCHDOG_WARNING);
        }
    }
    return $options;
}
function _hpoints_default_type_options(){
    return "other | Other";
}
/**
 * Helper function for whitelist/blacklist
 */
function hpoints_get_whitelist_nid(){
    $setting = variable_get('hpoints_whitelist_node','');
    //The setting string will be formatted like "Title of Node [nid: 99]"
    if($setting){
        $pos = strpos($setting, 'nid:');
        //clever use of PHP type coercion.
        $nid = substr($setting,$pos+4) + 0.0;
        //if the substr wasn't actually a number, $nid will be 0
        if($nid > 0){ return $nid; }
    }
    return '';
}

/**
 * Checks the settings to determine whether or not the complearning form
 * is currently open
 */
function hpoints_form_is_open(){
    $open = variable_get('hpoints_date_open',null);
    $close = variable_get('hpoints_date_close',null);
    if($open){
        $openstr = "{$open['year']}-{$open['month']}-{$open['day']} 00:00:00";
        $opentime = strtotime($openstr);
        drupal_set_message("Form opens on $openstr ($opentime)");
    }else{
        $open = 0;
    }
    if($close){
        $closestr = "{$close['year']}-{$close['month']}-{$close['day']} 23:59:00";
        $closetime = strtotime($closestr);
        drupal_set_message("Form closes on $closestr ($closetime)");
    }else{
        $close = PHP_INT_MAX;
    }
    return (time() > $opentime) && (time() < $closetime);
}

/*
 * Implements hook_views_bulk_operations_object_info
 * 
 * This hook tells Views Bulk Operations (VBO) that bulk operations
 * are supported for the 'complearning' type and how to access the table.
 */
function hpoints_views_bulk_operations_object_info(){
    return array(
        'complearning' => array(
            'type' => 'complearning',
            'base_table' => 'h_cl',
            'load' => 'hdata_cl_load',
            'oid' => 'id',
            'title' => 'id',
            'access' => '_hpoints_cl_review_access',
        ),
    );
}

/**
 * Implements hook_views_api
 * 
 * This tells Views that hcomplearn has a views.inc file.
 */
function hpoints_views_api(){
    return array('api'=>2);
}

/*----------------Access Callbacks------------------*/

/**
 * Allows access if the user is an active student and has permission to
 * submit comp learning.
 */
//VERDICT: unnecessary, replace with user_access
//Has role Honors or Faculty is all that's needed.
function _hpoints_form_access(){
    global $user;
    if($user->uid != 0){
        return hdata_user_is_active_student(array('uid' => $user->uid));
    }else{
        return false;
    }
}

//VERDICT: why is this even in hcomplearn?
/**
 * Allows access to the reviewing pages if the user has the
 * 'review complementary learning' permission or is the superuser (UID 1)
 */
function _hpoints_cl_review_access($op,$submission=null,$account=null){
    if(is_numeric($op)){
        $account = user_load($op);
    }
    if (empty($account)) {
        $account = $GLOBALS['user'];
    }
    //TODO: different perms
    return $account->uid == 1 || user_access('review complementary learning',$account) ||
            user_access('administer honors status',$account);
}
