<?php
function haddrole_user($op, &$edit, &$account, $category = NULL)
{
	if ($op=='login')
	{
		global $user;
		//variable_get retrieves system variables.  here we retrieve our variable 'haddrole_rid'
		$rid = variable_get('haddrole_rid',0);
		
		//the variable wasn't set in the database
		//this means that we haven't ever tried to retrieve the role.
		if ($rid == 0){ 
			$rs = db_query("SELECT rid FROM {role} WHERE name = '%s'",'Honors');
			if($result = db_fetch_object($rs)){
				$rid = $result->rid;
			}else{//there is no role called 'Honors'
				//set rid to -1 so that we don't check again.
				$rid = -1;
			}
			variable_set('haddrole_rid',$rid);
		}
				
		if ($rid == -1){
			drupal_set_message(t('You need to create a role called Honors and reinstall haddrole.'),'warning');
		}
		else
		{
			$roleName = db_result(db_query("SELECT r.name FROM {role} r WHERE r.name = '%s'", $role_name));
			if (!isset($user->roles[$rid]))
			{
				//load hstatus db api
				module_load_include('inc','hstatus','includes/hstatus.db');
				if(hstatus_ishonors($user->uid)){
					$roles = $user->roles + array($rid => $roleName);
					user_save($user, array('roles' => $roles));
				}
			}
		}
	}
}
